# Generated by Django 5.2.1 on 2025-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Unit', models.CharField(choices=[('Unit - 1', 'Unit - 1'), ('Unit - 2', 'Unit - 2'), ('Unit - 3', 'Unit - 3'), ('Unit - 4', 'Unit - 4'), ('Unit - 5', 'Unit - 5')], max_length=20)),
                ('Complaint', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('Completed', models.BooleanField(default=False)),
            ],
        ),
    ]
