# Generated by Django 5.2.1 on 2025-05-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electrician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='EndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
