# Generated by Django 5.2.1 on 2025-06-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electrician', '0002_complaint_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='AssignDept',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('IT', 'IT')], default='Electrician', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Priority',
            field=models.CharField(choices=[('⚪ Low', '⚪ Low'), ('🟡 Medium', '🟡 Medium'), ('🟠 Important', '🟠 Important'), ('🔴 Urgent', '🔴 Urgent')], default='⚪ Low', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='Rating',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='Unit',
            field=models.CharField(choices=[('Office', 'Office'), ('Unit - 1', 'Unit - 1'), ('Unit - 2', 'Unit - 2'), ('Unit - 3', 'Unit - 3'), ('Unit - 4', 'Unit - 4'), ('Unit - 5', 'Unit - 5')], max_length=20),
        ),
    ]
