# Generated by Django 5.2.1 on 2025-06-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electrician', '0006_alter_complaint_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Rating',
            field=models.CharField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐', max_length=20, null=True),
        ),
    ]
